### PR TITLE
Added repl.it support for uptimerobot!

### PR DESCRIPTION
**Pull request by NotSwaraj**
I just created a webserver in comments.

### CODE REVIEW

**Comment by NotSwaraj** [comment]
Make sure to add env token thingy

**Comment by Vedza** [comment]
Hey, Thanks for your pr ! This will be used on replit branch. I just need to find a way to deploy replit branch when we click on the button.

**Comment by NotSwaraj** [comment]
os.getEnv("TOKEN")

**Comment by Vedza** [comment]
> os.getEnv("TOKEN")

I already did env part for heroku 👍

**Comment by NotSwaraj** [comment]
Hi, Thank you for responding, heres how to host it on replit:
https://repl.it/claim?code=techwithtim  - go here and claim your free hacker plan for 90 days
https://repl.it/@NotSwarajv2/ScrawnyCriminalRatios  -  fork this repl and switch it to private
fill out settings.json 
and simple hit run
the sniper should be deployed!
now for 24/7 simply copy this link
Screen Shot 2021-01-24 at 15 06 16
(yours would be different)
than go to uptimerobot.com and register/login
than click new moniter 
Screen Shot 2021-01-24 at 15 07 50
Should look something like that but replace your url!
And done. Your good to go your sniper is 24/7

**Comment by NotSwaraj** [comment]
Also make sure to click Create moniter after filling it out

**Comment by DarkGD123** [comment]
hmm does this make this stuff seen on public when run on replit right?

**Comment by sonicm35** [comment]
> Hi, Thank you for responding, heres how to host it on replit:
> https://repl.it/claim?code=techwithtim - go here and claim your free hacker plan for 90 days
> https://repl.it/@NotSwarajv2/ScrawnyCriminalRatios - fork this repl and switch it to private
> fill out settings.json
> and simple hit run
> the sniper should be deployed!
> now for 24/7 simply copy this link
> Screen Shot 2021-01-24 at 15 06 16
> (yours would be different)
> than go to uptimerobot.com and register/login
> than click new moniter
> Screen Shot 2021-01-24 at 15 07 50
> Should look something like that but replace your url!
> And done. Your good to go your sniper is 24/7

image

**Pull request closed without merging**
