### PR TITLE
Update settings.json

### PR DESCRIPTION
**Pull request by RicTom776**

### CODE REVIEW

**Comment by Vedza** [comment]
Change your password, you just leaked your token.

**Comment by RicTom776** [comment]
what?? wdym

**Comment by Vedza** [comment]
You pushed your token on your public repo and also opened a pull request on my repo so everybody can see it. Just change your discord password and it will change your token. You can put your token on heroku, you don't need to push it on github

**Comment by RicTom776** [comment]
actually thanks for telling, i don't really use github much so i didnt know
i leaked my token. Though i changed my password!

**Comment by Vedza** [comment]
No problem! Be careful next time

**Pull request closed without merging**
